FLASK_APP='run.py'
FLASK_ENV='development'
SECRET_KEY='your-super-secret-key'
DATABASE_URL='sqlite:///app.db'
DATABASE_URL_DEV='sqlite:///dev_app.db'
DATABASE_TEST_URL='sqlite:///test.db'
DEBUG=True
GOOGLE_CLIENT_ID = "875921665781-kvapofau0re4k648u57a2qffrc159e75.apps.googleusercontent.com"
MAIL_SERVER = 'live.smtp.mailtrap.io'
MAIL_USERNAME = 'api'
MAIL_PASSWORD = 'e89e8108fb6fa593d1c837769eb3e3e3'
DEFAULT_FROM_EMAIL = 'hello@demomailtrap.com'
MAIL_PORT = 587
MAIL_USE_SSL = False
MAIL_USE_TLS = True
CELERY_BROKER_URL="redis://redis:6379/0"
CELERY_RESULT_BACKEND="redis://redis:6379/0"