version: "3.9"

services:
  redis:
    image: redis
  
  web:
    build:
      context: .
      target: dev-container
    container_name: web
    ports:
      - "0.0.0.0:5001:5001"
    volumes:
      - .:/app/:delegated
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://chefmode:chefmodedb@chef_mode_db:5432/chef_mode_backend
      - SECRET_KEY='MY SECRET'
    networks:
      - default
    depends_on:
      - chef_mode_db

  celery:
    build: .
    env_file:
      - .env
    environment:
      -  FLASK_DEBUG=1
      - APP_SETTINGS=app.config.DevelopmentConfig
    volumes:
      - .:/app
    command: celery -A app.extensions.celery worker --loglevel=info
    depends_on:
      - redis
      - web

  chef_mode_db:
    image: postgres:16-alpine
    hostname: chef_mode_db
    container_name: chef_mode_db
    environment:
      - POSTGRES_PASSWORD=chefmodedb
      - POSTGRES_USER=chefmode
    networks:
      - default
    ports:
      - "0.0.0.0:5432:5432/tcp"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
