version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py run -h 0.0.0.0 -p 5000
    container_name: web
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@chef_mode_backend:5432/chef_mode_backend
      - SECRET_KEY='MY SECRET'
    depends_on:
      - chef_mode_backend
    links:
      - chef_mode_backend

  chef_mode_backend:
    container_name: ChefModeBackend
    build:
      context: ./infrastructure/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PROFILE=postgres
      - POSTGRES_PASSWORD=postgres
