
services:
  redis:
    image: redis

  web:
    build:
      context: .
      target: dev-container
    container_name: web
    ports:
      - "0.0.0.0:5001:5001"
    volumes:
      - .:/app/:delegated
    networks:
      - default
    depends_on:
      - chef_mode_db
    restart: always

  celery:
    build: .
    restart: always
    volumes:
      - .:/app
    command: celery -A manage.celery worker --loglevel=info
    depends_on:
      - redis
      - web

  chef_mode_db:
    image: postgres:16-alpine
    hostname: chef_mode_db
    container_name: chef_mode_db
    environment:
      - POSTGRES_PASSWORD=chefmodedb
      - POSTGRES_USER=chefmode
    networks:
      - default
    ports:
      - "0.0.0.0:5432:5432/tcp"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
