version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py run -h 0.0.0.0 -p 5000
    container_name: web
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=infrastructure.framework.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@chefmode:5432/pentest_db
      - SECRET_KEY='MY SECRET'
    depends_on:
      - chefmode
    links:
      - chefmode

  chefmode:
    container_name: chefmode
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PROFILE=postgres
      - POSTGRES_PASSWORD=postgres