"""empty message

Revision ID: 030c72a64532
Revises: 29b2665ba133
Create Date: 2024-11-24 19:50:04.253363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030c72a64532'
down_revision = '29b2665ba133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymous_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymous_user', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
