"""empty message

Revision ID: 14020c1afe81
Revises: 83f2c5555670
Create Date: 2024-11-29 18:00:32.532741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14020c1afe81'
down_revision = '83f2c5555670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_token_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_token_jti'))

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
