"""empty message

Revision ID: 405b3b71abb6
Revises: ff6c52a21362
Create Date: 2024-12-04 17:48:28.765712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405b3b71abb6'
down_revision = 'ff6c52a21362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
