"""empty message

Revision ID: 503e6f4d75af
Revises: 3dfdcfd93d0b
Create Date: 2024-12-04 18:13:44.266235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503e6f4d75af'
down_revision = '3dfdcfd93d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maillist',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maillist')
    # ### end Alembic commands ###
