"""empty message

Revision ID: 69725c847fe4
Revises: 98ddc11e4970
Create Date: 2024-12-14 13:51:59.707284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69725c847fe4'
down_revision = '98ddc11e4970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['origin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
