"""empty message

Revision ID: 7470f22ac62e
Revises: 3dfb2b9059c4
Create Date: 2024-12-05 04:26:18.864801

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7470f22ac62e'
down_revision = '3dfb2b9059c4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('servings',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='servings::integer')


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('servings',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               postgresql_using='servings::text'
        )

    # ### end Alembic commands ###
