"""empty message

Revision ID: 786b799eae1d
Revises: d51ea7fb87cc
Create Date: 2024-11-25 15:30:03.154333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786b799eae1d'
down_revision = 'd51ea7fb87cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reset_token', type_='unique')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_reset_token', ['reset_token'])

    # ### end Alembic commands ###
