"""empty message

Revision ID: 83f2c5555670
Revises: 8eb72ff3f8a8
Create Date: 2024-11-28 04:17:37.066228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f2c5555670'
down_revision = '8eb72ff3f8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('expires_in_days', sa.Integer(), nullable=True),
    sa.Column('max_receipts', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('subscription_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('subscription', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('subscription_id', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('latest_invoice', sa.Text(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('payment_frequency', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_membership')
    op.drop_table('subscription')
    # ### end Alembic commands ###
