"""empty message

Revision ID: c796a00bfb3c
Revises: 6ccfc741c14d
Create Date: 2025-01-30 15:45:01.307917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c796a00bfb3c'
down_revision = '6ccfc741c14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymous_user_recipe', schema=None) as batch_op:
        batch_op.drop_constraint('anonymous_user_recipe_recipe_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('anonymous_user_recipe_anonymous_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'anonymous_user', ['anonymous_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonymous_user_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('anonymous_user_recipe_anonymous_user_id_fkey', 'anonymous_user', ['anonymous_user_id'], ['id'])
        batch_op.create_foreign_key('anonymous_user_recipe_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
