"""empty message

Revision ID: d51ea7fb87cc
Revises: 030c72a64532
Create Date: 2024-11-25 15:23:37.371167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51ea7fb87cc'
down_revision = '030c72a64532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        # Provide a name for the unique constraint
        batch_op.create_unique_constraint('uq_reset_token', ['reset_token'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
