"""empty message

Revision ID: d66178d527f6
Revises: 5e71482d0f4c
Create Date: 2024-12-13 10:13:57.559006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66178d527f6'
down_revision = '5e71482d0f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mainmail',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mainmail')
    # ### end Alembic commands ###
