"""empty message

Revision ID: fe01ef60f2f3
Revises: 405b3b71abb6
Create Date: 2024-12-04 18:04:36.367405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe01ef60f2f3'
down_revision = '405b3b71abb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=2024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('google_token',
               existing_type=sa.String(length=2024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###
